export const legalConfig = {
  projectName: 'PRIME ACADEMY',
  projectDescription: 'онлайн-подготовка по физике и репетиторские занятия',
  siteDomain: 'TODO_DOMAIN',
  operatorFullName: 'Кузнецов Кирилл Алексеевич',
  operatorStatus: 'самозанятый',
  operatorInn: 'TODO_INN',
  operatorCity: 'Москва',
  operatorEmail: 'kirilkuznecov0018@gmail.com',
  personalDataContactName: 'Кирилл Кузнецов',
  telegramContact: 'https://t.me/Total_victories',
  telegramContactLabel: '@Total_victories',
  telegramChannel: 'https://t.me/physicspace',
  telegramChannelLabel: '@physicspace',
  effectiveDate: 'TODO_EFFECTIVE_DATE',
  privacyVersion: '1.0',
  consentVersion: '1.0',
  marketingConsentVersion: '1.0',
  termsVersion: '1.0',
  usesCookies: false,
  usesAnalytics: false,
  hasPaymentsOnSite: false,
  hasRegistration: false,
  hasPersonalAccount: false,
  hasLeadFormSubmission: false,
} as const

export const legalLinks = [
  { label: 'Политика обработки персональных данных', href: '/privacy' },
  { label: 'Согласие на обработку персональных данных', href: '/personal-data-consent' },
  { label: 'Согласие на информационные сообщения', href: '/marketing-consent' },
  { label: 'Пользовательское соглашение', href: '/terms' },
  { label: 'Cookies и аналитика', href: '/cookies' },
]
